export const TERMINAL_ACCESS_TOKEN_UPDATE = 'TERMINAL_ACCESS_TOKEN_UPDATE';
export const TERMINAL_ID_UPDATE = 'TERMINAL_ID_UPDATE';
export const TERMINAL_ONLINE_UPDATE = 'TERMINAL_ONLINE_UPDATE';
export const TERMINAL_UPDATE = 'TERMINAL_UPDATE';
