export const TERMINAL_ACCESS_TOKEN_UPDATE = "TERMINAL_ACCESS_TOKEN_UPDATE";
export const TERMINAL_ID_UPDATE = "TERMINAL_ID_UPDATE";
export const TERMINAL_UPDATE = "TERMINAL_ID_UPDATE";

export const API_DEFAULT_URL = 'https://api.simpozio.com/v2';
