export const NEXT_DO_INVALIDATE = 'NEXT_DO_INVALIDATE';
export const NEXT_DO_NEXT = 'NEXT_DO_NEXT';
export const NEXT_INVALIDATE_EVENT = 'NEXT_INVALIDATE_EVENT';
export const NEXT_EVENT = 'NEXT_EVENT';
export const NEXT_SET_WAIT_FOR = ' NEXT_SET_WAIT_FOR';
